# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/camilo/Proyectos/qgis/python/plugins/processingmanager/dialog.ui'
#
# Created: Thu Dec 15 23:34:28 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_runDialog(object):
    def setupUi(self, runDialog):
        runDialog.setObjectName(_fromUtf8("runDialog"))
        runDialog.resize(640, 480)
        runDialog.setWindowTitle(QtGui.QApplication.translate("runDialog", "Run Processing module ", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(runDialog)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(runDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mandatoryTab = QtGui.QWidget()
        self.mandatoryTab.setObjectName(_fromUtf8("mandatoryTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mandatoryTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mandatoryScroll = QtGui.QScrollArea(self.mandatoryTab)
        self.mandatoryScroll.setFrameShape(QtGui.QFrame.NoFrame)
        self.mandatoryScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mandatoryScroll.setWidgetResizable(True)
        self.mandatoryScroll.setObjectName(_fromUtf8("mandatoryScroll"))
        self.mandatoryWidget = QtGui.QWidget()
        self.mandatoryWidget.setGeometry(QtCore.QRect(0, 0, 521, 388))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mandatoryWidget.sizePolicy().hasHeightForWidth())
        self.mandatoryWidget.setSizePolicy(sizePolicy)
        self.mandatoryWidget.setObjectName(_fromUtf8("mandatoryWidget"))
        self.mandatoryForm = QtGui.QFormLayout(self.mandatoryWidget)
        self.mandatoryForm.setObjectName(_fromUtf8("mandatoryForm"))
        self.mandatoryScroll.setWidget(self.mandatoryWidget)
        self.verticalLayout_2.addWidget(self.mandatoryScroll)
        self.tabWidget.addTab(self.mandatoryTab, _fromUtf8(""))
        self.optionalTab = QtGui.QWidget()
        self.optionalTab.setObjectName(_fromUtf8("optionalTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.optionalTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.optionalScroll = QtGui.QScrollArea(self.optionalTab)
        self.optionalScroll.setFrameShape(QtGui.QFrame.NoFrame)
        self.optionalScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.optionalScroll.setWidgetResizable(True)
        self.optionalScroll.setObjectName(_fromUtf8("optionalScroll"))
        self.optionalWidget = QtGui.QWidget()
        self.optionalWidget.setGeometry(QtCore.QRect(0, 0, 521, 175))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionalWidget.sizePolicy().hasHeightForWidth())
        self.optionalWidget.setSizePolicy(sizePolicy)
        self.optionalWidget.setObjectName(_fromUtf8("optionalWidget"))
        self.optionalForm = QtGui.QFormLayout(self.optionalWidget)
        self.optionalForm.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.optionalForm.setObjectName(_fromUtf8("optionalForm"))
        self.optionalScroll.setWidget(self.optionalWidget)
        self.verticalLayout.addWidget(self.optionalScroll)
        self.advancedButton = QtGui.QPushButton(self.optionalTab)
        self.advancedButton.setText(QtGui.QApplication.translate("runDialog", "Show &Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedButton.setCheckable(True)
        self.advancedButton.setObjectName(_fromUtf8("advancedButton"))
        self.verticalLayout.addWidget(self.advancedButton)
        self.advancedScroll = QtGui.QScrollArea(self.optionalTab)
        self.advancedScroll.setFrameShape(QtGui.QFrame.NoFrame)
        self.advancedScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.advancedScroll.setWidgetResizable(True)
        self.advancedScroll.setObjectName(_fromUtf8("advancedScroll"))
        self.advancedWidget = QtGui.QWidget()
        self.advancedWidget.setGeometry(QtCore.QRect(0, 0, 521, 174))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advancedWidget.sizePolicy().hasHeightForWidth())
        self.advancedWidget.setSizePolicy(sizePolicy)
        self.advancedWidget.setObjectName(_fromUtf8("advancedWidget"))
        self.advancedForm = QtGui.QFormLayout(self.advancedWidget)
        self.advancedForm.setObjectName(_fromUtf8("advancedForm"))
        self.advancedScroll.setWidget(self.advancedWidget)
        self.verticalLayout.addWidget(self.advancedScroll)
        self.tabWidget.addTab(self.optionalTab, _fromUtf8(""))
        self.textTab = QtGui.QWidget()
        self.textTab.setObjectName(_fromUtf8("textTab"))
        self.textLayout = QtGui.QVBoxLayout(self.textTab)
        self.textLayout.setObjectName(_fromUtf8("textLayout"))
        self.text = QtGui.QTextBrowser(self.textTab)
        self.text.setOpenExternalLinks(True)
        self.text.setObjectName(_fromUtf8("text"))
        self.textLayout.addWidget(self.text)
        self.tabWidget.addTab(self.textTab, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.logTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.logText = QtGui.QTextBrowser(self.logTab)
        self.logText.setObjectName(_fromUtf8("logText"))
        self.verticalLayout_3.addWidget(self.logText)
        self.tabWidget.addTab(self.logTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttons = QtGui.QDialogButtonBox(runDialog)
        self.buttons.setOrientation(QtCore.Qt.Vertical)
        self.buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Open|QtGui.QDialogButtonBox.Save)
        self.buttons.setObjectName(_fromUtf8("buttons"))
        self.gridLayout.addWidget(self.buttons, 0, 2, 2, 1)
        self.statusBar = QtGui.QStatusBar(runDialog)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.gridLayout.addWidget(self.statusBar, 3, 0, 1, 3)

        self.retranslateUi(runDialog)
        QtCore.QObject.connect(self.buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), runDialog.reject)
        QtCore.QObject.connect(self.buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), runDialog.accept)
        QtCore.QObject.connect(self.advancedButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.advancedScroll.setVisible)
        QtCore.QMetaObject.connectSlotsByName(runDialog)

    def retranslateUi(self, runDialog):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mandatoryTab), QtGui.QApplication.translate("runDialog", "Mandatory Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionalTab), QtGui.QApplication.translate("runDialog", "Optional Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.textTab), QtGui.QApplication.translate("runDialog", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), QtGui.QApplication.translate("runDialog", "Log", None, QtGui.QApplication.UnicodeUTF8))

